version = 0.1
[default.deploy.parameters]
stack_name = "meadmandelbrot"
resolve_s3 = true
s3_prefix = "meadmandelbrot"
region = "eu-west-2"
capabilities = "CAPABILITY_IAM"
image_repositories = ["MeadMandelbrotFunction=939027885851.dkr.ecr.eu-west-2.amazonaws.com/meadmandelbrotd18ae537/meadmandelbrotfunctionbd344d2arepo"]
