version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "mandelbrotMead"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-q72rntpmpzju"
s3_prefix = "mandelbrotMead"
region = "eu-west-1"
capabilities = "CAPABILITY_IAM"
image_repositories = ["MeadMandelbrotFunction=939027885851.dkr.ecr.eu-west-1.amazonaws.com/mandelbrotmead5c07d184/meadmandelbrotfunctionbd344d2arepo"]
