AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: SAM template for Mandelbrot function for my website

Globals:
  Api:
    Cors:
      AllowMethods: "'GET,POST,OPTIONS'"
      AllowHeaders: "'content-type'"
      AllowOrigin: "'*'"
      AllowCredentials: "'*'"
  Function:
    Architectures:
      # - x86_64
      - arm64
    Timeout: 60

Resources:
  MeadMandelbrotFunction:
    Type: AWS::Serverless::Function
    Properties:
      Description: "A lambda that generates an image from the Mandelbrot Set."
      PackageType: Image
      Events:
        MeadMandelbrot:
          Type: Api
          Properties:
            Path: /mandelbrot
            Method: post
      MemorySize: 10240
    Metadata:
      Dockerfile: Dockerfile
      DockerContext: .

Outputs:
  MeadMandelbrotApi:
    Description: "API Gateway endpoint URL for Mead Mandelbrot function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/mandelbrot"
