version = 0.1
[default.deploy.parameters]
stack_name = "mead-nbody"
resolve_s3 = true
s3_prefix = "mead-nbody"
region = "eu-west-2"
profile = "personal"
capabilities = "CAPABILITY_IAM"
image_repositories = [
    "MeadNbodyFunction=816069155046.dkr.ecr.eu-west-2.amazonaws.com/meadnbodyca117dc0/meadnbodyfunction40fb9383repo",
]
