AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  SAM template for my website

Globals:
  Api:
    Cors:
      AllowMethods: "'GET,POST,OPTIONS'"
      AllowHeaders: "'content-type'"
      AllowOrigin: "'*'"
      AllowCredentials: "'*'"
  Function:
    Architectures:
      # - x86_64
      - arm64 # digiLab M2 Mac
    Timeout: 15

Resources:
  MeadNbodyFunction:
    Type: AWS::Serverless::Function
    Properties:
      Description: "A lambda that generates an image from a universe."
      PackageType: Image
      Events:
        MeadNbody:
          Type: Api
          Properties:
            Path: /nbody
            Method: post
      # MemorySize: 10240 # digiLab
      MemorySize: 3008 # Personal
      Environment:
        Variables:
          TWINLAB_URL: { { TWINLAB_URL } }
          TWINLAB_USER: { { TWINLAB_USER } }
          TWINLAB_API_KEY: { { TWINLAB_API_KEY } }
    Metadata:
      Dockerfile: Dockerfile
      DockerContext: .

Outputs:
  MeadNbodyApi:
    Description: "API Gateway endpoint URL for Mead Nbody function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/nbody"
